### ISSUE TITLE
Animation distorted in case of changing window size.

### ISSUE THREAD

**Issue by FlaviusHouk** [FlaviusHouk/TagEditor#1]
**Steps to reproduce:**

1. Open app;
2. Start animation and wait until it ends;
3. Change window size(for example maximize it);
4. Observe tag edition screen;

**Comment by danyil-hryhoriev** [comment]
Fixed with [a6dcf4f33240d7887b2b46084c70a02ff1232234](https://github.com/FlaviusHouk/TagEditor/commit/a6dcf4f33240d7887b2b46084c70a02ff1232234)
