### ISSUE TITLE
Create algorythm to find Image moda.

### ISSUE THREAD

**Issue by danyil-hryhoriev** [FlaviusHouk/TagEditor#10]

**Comment by FlaviusHouk** [comment]
Related to (2706ffe)[2706ffee275c69b2d3dd888ceef8a8eb4e6812fe]

Currently only BRG 24 bit images are supported. Color is not 100% moda of the picture, but it works quite good and fast.

**Comment by FlaviusHouk** [comment]
Implemented class for cluster analysis. Stability and speed improvements are made. [09dbaf1](https://github.com/FlaviusHouk/TagEditor/commit/09dbaf1f8e0b051d449e85b3b71ec9b9be758cda) commit.
