### ISSUE TITLE
Provide an opportunity to write in tag.

### ISSUE THREAD

**Issue by danyil-hryhoriev** [FlaviusHouk/TagEditor#14]

**Comment by FlaviusHouk** [comment]
Related to commit [da76fed](https://github.com/FlaviusHouk/TagEditor/commit/310f742030741002561660d92679df770a403928)
Please connect new methods to UI.

**Comment by FlaviusHouk** [comment]
Added some fixes with commits [809c5cf](809c5cf757278eff44c23a3a04954ed16f837b57) and [3aa82c8](3aa82c8347ad9a32518e447df46a5fecdeb610d8). Please provide the rest of the tags for editing in UI.
