### ISSUE TITLE
Bug incorrect writing ISRC-code

### ISSUE THREAD

**Issue by danyil-hryhoriev** [FlaviusHouk/TagEditor#19]
After saving tags ISRC field in others Apllications has similar view "￿唀匀㔀㈀㘀㄀㌀㄀㜀㠀　㌀"

**Comment by FlaviusHouk** [comment]
![image](https://user-images.githubusercontent.com/13718310/44001660-a346b940-9e3e-11e8-8711-7fb6c57d5c00.png)

What do you think about this? Do you have other application to check ISRC?

**Comment by danyil-hryhoriev** [comment]
ViewModel part works perfectly and ISRC-code saves correctly
