### ISSUE TITLE
#2 Crash when get empty Length/Year from Tag

### ISSUE THREAD

**Issue by danyil-hryhoriev** [FlaviusHouk/TagEditor#2]
In Tag.cs - [184](https://github.com/FlaviusHouk/TagEditor/blob/master/TagManager/ID3v2/Tag.cs) Line

**Comment by FlaviusHouk** [comment]
Bug fixed with [f012ffb](https://github.com/FlaviusHouk/TagEditor/commit/f012ffb264e96b19d414cef8ddb071b060b61f63) commit.
