### ISSUE TITLE
Too little margins in TagView

### ISSUE THREAD

**Issue by FlaviusHouk** [FlaviusHouk/TagEditor#21]
![image](https://user-images.githubusercontent.com/13718310/43994257-de4b757c-9da2-11e8-8c06-ba05d888486f.png)

All groups should have more margin.

**Comment by danyil-hryhoriev** [comment]
Fixed by [7c4a532ecbfb663c9ab8a311f4900de89d9ab817](https://github.com/FlaviusHouk/TagEditor/commit/7c4a532ecbfb663c9ab8a311f4900de89d9ab817) commit
