### ISSUE TITLE
Grid Column splitter looks ugly

### ISSUE THREAD

**Issue by FlaviusHouk** [FlaviusHouk/TagEditor#22]
![image](https://user-images.githubusercontent.com/13718310/43994279-21e9d652-9da3-11e8-86d8-44d17aa72873.png)

Splitter does not have high to go from the top to the bottom.
Also it lies over the ListView's scrollbar.

**Comment by danyil-hryhoriev** [comment]
Fixed by [7c4a532ecbfb663c9ab8a311f4900de89d9ab817](https://github.com/FlaviusHouk/TagEditor/commit/7c4a532ecbfb663c9ab8a311f4900de89d9ab817) commit
