### ISSUE TITLE
Manage list view items.

### ISSUE THREAD

**Issue by FlaviusHouk** [FlaviusHouk/TagEditor#27]
User should have an opportunity to delete opened mp3 files or change it oisition via Drag&Drop.

**Comment by danyil-hryhoriev** [comment]
Fixed by [commit](https://github.com/FlaviusHouk/TagEditor/commit/64cc55a83195d45e8fb74be1163ebaaba03b6859)

**Comment by danyil-hryhoriev** [comment]
Opportunity for deleting of songs was provided. The drag&drop feature needs to discuss and if needs will be opened as new feature.
